# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Main prompt format (Left side)
format = """$all"""

# Right side prompt format
right_format = """$time"""

[time]
disabled = false
# %I = Hour (01-12), %M = Minute, %p = AM/PM
time_format = "%I:%M %p" 
format = '[    $time ]($style)'
style = "bold purple"

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✖](bold red) '

[custom.bash]
command = "echo bash"
description = "Displays 'bash' if in bash shell"
when = '[ "$STARSHIP_SHELL" = "bash" ]'
format = '[$output](cyan bold) '
disabled = false

[line_break]
disabled = true